#if !canImport(ObjectiveC)
import XCTest

extension LRUCacheTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LRUCacheTests = [
        ("testLRUEvictsFirstAdded", testLRUEvictsFirstAdded),
        ("testLRUEvictsOldest", testLRUEvictsOldest),
        ("testLRUHoldCapacity", testLRUHoldCapacity),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LRUCacheTests.__allTests__LRUCacheTests),
    ]
}
#endif
